### ISSUE TITLE
Trouble in associating models

### ISSUE THREAD

**Issue by cong96bg** [asielh1n1/zunkernel#1]
I have read and followed the instructions in sequelizejs website but still stuck in associating models. The error is "the X is not associated to the Y". Please give me a hand!

**Comment by asielh1n1** [comment]
try it this way that works well for me in a project I did:
zun.admin.model.user.belongsTo(zun.admin.model.rol,{foreignKey:'id_rol'});
zun.admin.model.rol.hasMany(zun.admin.model.user,{foreignKey:'id'});

// Relacion N a N entre rol y permissions
zun.admin.model.rol.belongsToMany(zun.admin.model.permissions, {through: 'roles_permissions'});
zun.admin.model.permissions.belongsToMany(zun.admin.model.rol, {through: 'roles_permissions'});

**Comment by cong96bg** [comment]
Thanks a lot! It works for me too. 
Another issue is that zun.db.Sequelize seems not to accept queries with such operations as $not, $like and $or. Any idea for such queries?

**Comment by asielh1n1** [comment]
zun.bundle_name.model.model_name.findAll({
			where:{
				id:req.body.id_request,
				$or:[
					{status:{$in:["pending","accepted"]}},
					{id_driver:req.session.user.id}
				]
			}
		})
		.then(function(data){})
